#!/usr/bin/env bash
set -euo pipefail

# Restore TG pg_dump -Fc into schema tg.* inside kb_ring database.
#
# Usage:
#   DUMP=server_exports/tg_93_77_185_71/<ts>/tg_digest.dump \
#   DATABASE_URL=postgresql://kb_ring:***@127.0.0.1:15432/kb_ring \
#   bash kb_ring/ops/step1_nil/restore_tg_dump_to_kb_ring.sh
#
# Notes:
# - This script rewrites schema references public -> tg.
# - Run on a test copy first.

DUMP="${DUMP:-}"
DATABASE_URL="${DATABASE_URL:-}"

if [[ -z "${DUMP}" || -z "${DATABASE_URL}" ]]; then
  echo "Usage: DUMP=... DATABASE_URL=... $0" >&2
  exit 2
fi

if [[ ! -f "${DUMP}" ]]; then
  echo "Dump file not found: ${DUMP}" >&2
  exit 1
fi

tmp_raw="$(mktemp)"
tmp_sql="$(mktemp)"
trap 'rm -f "${tmp_raw}" "${tmp_sql}"' EXIT

echo "[1/3] Exporting SQL from custom dump"
pg_restore --no-owner --no-privileges -f "${tmp_raw}" "${DUMP}"

echo "[2/3] Rewriting schema references public.* -> tg.*"
{
  echo "-- generated by restore_tg_dump_to_kb_ring.sh"
  echo "BEGIN;"
  echo "CREATE SCHEMA IF NOT EXISTS tg;"
  echo "SET search_path = tg, public;"
  perl -pe '
    s/\bSCHEMA public\b/SCHEMA tg/g;
    s/\bpublic\./tg./g;
    s/SET search_path = public, pg_catalog;/SET search_path = tg, pg_catalog;/g;
  ' "${tmp_raw}"
  echo "COMMIT;"
} > "${tmp_sql}"

echo "[3/3] Applying to kb_ring (${DATABASE_URL})"
psql "${DATABASE_URL}" -v ON_ERROR_STOP=1 -f "${tmp_sql}"

echo "OK: TG dump restored into schema tg.*"

